
MACs: [hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1, hmac-sha1-96]

Ciphers: [aes128-ctr, arcfour256, arcfour128, arcfour, aes128-cbc, 3des-cbc, aes128-gcm@openssh.com, aes256-gcm@openssh.com, chacha20-poly1305@openssh.com , aes128-ctr, aes192-ctr, aes256-ctr]
KexAlgos: [urve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group14-sha256, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1, diffie-hellman-group-exchange-sha1, diffie-hellman-group-exchange-sha256]
HostKeyAlgos: []
