name: 'build JMS tool'
author: 'Eric Lee'
description: 'Build JMS tool'
runs:
  using: "composite"
  steps:
    - run: echo "current dir" ${pwd}
      shell: bash
    - id: build-go-main
      run: |
        go build -o jmstool_${go env var GOOS} .
        ls -al
      shell: bash