name: 'build JMS tool'
author: 'Eric Lee'
description: 'Build JMS tool'
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.go-version }}  ${{ inputs.go-os }} ${{ inputs.go-arch }}
      shell: bash
    - id: build-go-main
      run: |
        go build -o jmstool_${{ inputs.go-os }} .
        ls -al
      shell: bash