name: 'build JMS tool'
author: 'Eric Lee'
description: 'Build JMS tool'
inputs:
  build_os:
    description: build os
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "current dir" ${pwd}
      shell: bash
    - id: build-go-main
      run: |
        go build -o jmstool_${{ inputs.build_os }} .
        ls -al
      shell: bash